### ISSUE TITLE
Is the demo working?

### ISSUE THREAD

**Issue by mikethepipe** [EsriUK/arcgis-dijit-drilldown#1]
Hi,

Is the [demo](http://appsstage.esriuk.com/app/Vanilla-Drilldown-demo/5/wmt/view/67eefa85647b496ba57e4bb0229129de/index.html) working? I thought when I looked at it yesterday it was working but just now when I put in some Edinburgh addresses and search it's not returning any results. Firebug says:

TypeError: a[0].PickListItems is undefined

which is the same error message I get when I try to add it into my own javascript API map.

Cheers,
Mike

**Comment by danbatsb** [comment]
Hi Mike

Thanks for letting us know, the issue has been sorted and the demo should be working now.

Cheers
Seth

**Comment by mikethepipe** [comment]
No problem. I'm having a problem getting the drilldown widget to work in my javascript map, I don't suppose you could please help?

**Comment by danbatsb** [comment]
Mike, if you send me an email with some details then I can hopefully help you out. sbatterby@esriuk.com

**Comment by mikethepipe** [comment]
That's great, thanks very much
